Phase08-EFCore and its tests completed.
Star-Academy/Winter99-Co-op-Hossein-Aghaei pull request #5
Opened 2021-03-08 08:28 UTC by hoseinaghaei

2021-03-08 21:01 UTC, mostmand requested changes
احسنت بسیار عالی
یه کم فایل‌های اضافه از جمله
obj, bin, ...
رو با اجازه از ریپوت حذف کردم
یه سری کامنت هم گذاشتم

2021-03-08 21:01 UTC, mostmand commented on phase08/search/Controller.cs
> +        public DocContainer SplitInputIntoSeparateDocs(string inputSentence)
این تابع چرا پابلیک است در حالی که تنها مشتری آن داخل همین کلاس است؟
اگر صرفا برای تست این اتفاق افتاده بهتر است این تابع به کلاس دیگری منتقل شود

2021-03-08 21:01 UTC, mostmand commented on phase08/search/Controller.cs
> +                NoSignWords = noSignWords, PlusSignWords = plusSignWords, MinusSignWords = minusSignWords
هر کدوم رو بذار تو یه خط تا خواناتر باشه

2021-03-08 21:01 UTC, mostmand commented on phase08/search/DocContainer.cs
> +                   NoSignWords.ToString() == b1.NoSignWords.ToString() &&
این طرز تساوی چک کردن یه کم عجیبه
این که هش ست رو 
ToString()
کردی

2021-03-08 21:01 UTC, mostmand commented on phase08/search/DocFileReader.cs
> +                FileContent = File.ReadAllText(x).ToLower()
این خط می‌تونه اکسترکت متد بشه

2021-03-08 21:01 UTC, mostmand commented on phase08/search/DocumentRepository.cs
> +            return _searchContext.Docs.Where(x => docs.Contains(x.Name)).Select(x => x.Name).ToList();
یه کم اینتر بزن تو هر خط یه دات بیش‌تر نزن که کد خواناتر باشه

2021-03-08 21:01 UTC, mostmand commented on phase08/search/DocumentRepository.cs
> +            return _searchContext.Docs.Where(x => docs.Contains(x.Name)).Select(x => x.Name).ToList();
مثلا
select
بره تو یه خط و 
ToList
هم تو یه خط دیگه

2021-03-08 21:01 UTC, mostmand commented on phase08/search/DocumentRepository.cs
> +            var xWord = _searchContext.Words.Where(x => duplicateWords.Contains(x.Term));
به جای
xWord
اسم مناسب‌تری برای متغیر بذار

2021-03-08 21:01 UTC, mostmand commented on phase08/search/DocumentRepository.cs
> +            return _searchContext.Words.Any(x => x.Term == word)
این جا دو تا کوئری زده میشه اگه اون کلمه توی دیتابیس باشه بهتره این طوری بزنی:
```csharp
var existingWord = _searchContext.Words.Include(x => x.DocsContainer)
    .FirstOrDefault(x => x.Term == word);
if (existingWord == default)
    return new HashSet<string>();

return existingWord.DocsContainer.Select(x => x.Name)
    .ToHashSet();
```

2021-03-08 21:01 UTC, mostmand commented on phase08/search/IndexCreator.cs
> +            foreach (var doc in allDocuments.Keys.Except(_documentRepository.GetExistedDocs(allDocuments.Keys.ToList())))
این خط خیلی طولانی شده بیش‌تر متغیر تعریف کن:
```csharp
var allDocs = allDocument.Keys.ToList();
var existingDocuments = _documentRepository.GetExistedDocs(allDocs);
var newDocuments = allDocuments.Keys.Except(existingDocuments);
foreach (var doc in newDocuments)
{
    ...
}
```
در ضمن
ExistingDocs
درسته و 
ExistedDocs
غلطه

2021-03-08 21:01 UTC, mostmand commented on phase08/search/Processor.cs
> +            return noSignWords.Select(x => _documentRepository.GetDocsContain(x))
شور
Linq
رو در آوردن!😂

2021-03-08 21:01 UTC, mostmand commented on phase08/searchTest/DocFileReaderTests.cs
> +            var result = _sut.ScanData();
بهتره
path
به جای این که توی
consturctor
کلاس
DocFileReader
گرفته بشه توی ورودی تابع
ScanData
گرفته بشه

2021-03-08 21:01 UTC, mostmand commented on phase08/searchTest/DocumentRepositoryForTest.cs
> +    public class DocumentRepositoryForTest : IDocumentRepository
به عنوان یه کلاس
mock
زیاد از حد پیچیده است

2021-03-08 21:05 UTC, hoseinaghaei commented on phase08/search/Controller.cs
> +                NoSignWords = noSignWords, PlusSignWords = plusSignWords, MinusSignWords = minusSignWords
سلام، حقیقتش اینو از فاز پیش کپی کردم بخاطر اونه، تصحیح میکنم

2021-03-08 21:06 UTC, hoseinaghaei commented on phase08/search/Controller.cs
> +        public DocContainer SplitInputIntoSeparateDocs(string inputSentence)
بله دقیقا بخاطر تست بود، میشه اصلا پرایوتش کنم؟ البته اگر مشکلی برای ماک کردنش پیش نیاد

2021-03-08 21:07 UTC, hoseinaghaei commented on phase08/search/DocContainer.cs
> +                   NoSignWords.ToString() == b1.NoSignWords.ToString() &&
وقتی برای هش ست تو استرینگ رو مقایسه میکنیم، فقط عناصر درونش باهم مقایسه میشه، در واقع رفرنس ها مقایسه نمیشه
اینو تست رانگ میشد مجبور شدم بذارم

2021-03-08 21:09 UTC, hoseinaghaei commented on phase08/search/DocumentRepository.cs
> +            return _searchContext.Words.Any(x => x.Term == word)
منظورتون از دیفالت همون نال هست؟

2021-03-08 21:11 UTC, hoseinaghaei commented on phase08/search/Processor.cs
> +            return noSignWords.Select(x => _documentRepository.GetDocsContain(x))
کل جذابیت سی شارپ به همینشه خدایی:))

2021-03-09 08:07 UTC, hoseinaghaei commented
Phase08-EFCore Completed

2021-03-09 08:08 UTC, merged