Phase10 nest
Star-Academy/Winter99-Co-op-Hossein-Aghaei pull request #6
Opened 2021-03-18 08:01 UTC by hoseinaghaei

ولیدیتور تست نداره چون حقیقتا اصلا نشد حالتی رو پیدا کنم که به این اررورها بخوره تا بتونم تست بنویسم براش!

2021-03-26 12:15 UTC, mahdimalverdi requested changes

2021-03-26 12:15 UTC, mahdimalverdi commented on phase10/elasticsearch/Controller.cs
> +                    plusSignWords = $"{plusSignWords} {word.Substring(1)}";
از تابع Trim با ورودی دادن استفاده کن

2021-03-26 12:15 UTC, mahdimalverdi commented on phase10/elasticsearch/SearchConnection/ElasticClientFactory.cs
> +            var uri = new Uri("http://localhost:9200");
در مورد فایل AppSetting.json بخون

2021-03-26 12:27 UTC, hoseinaghaei commented on phase10/elasticsearch/Controller.cs
> +                    plusSignWords = $"{plusSignWords} {word.Substring(1)}";
چیشد نفهمیدم؟

2021-03-28 14:45 UTC, mostmand requested changes

2021-03-28 14:45 UTC, mostmand commented on phase10/elasticsearch/Controller.cs
> +                    noSignWords = $"{noSignWords} {word}";
از
StringBuilder
یا از
string.Join
استفاده کن که از لحاظ پرفورمنسی بهتره البته اینجا تعداد کلمات احتمالا خیلی زیاد نیست ولی هر جا دیدی داری
for
می‌زنی و به یه استرینگ هی اضافه می‌کنی خوبه که از یکی از این دو مورد که گفتم استفاده کنی

2021-03-28 14:45 UTC, mostmand commented on phase10/elasticsearch/DocManager/DocFileReader.cs
> +        public Dictionary<string, string> ScanData(string directoryPath)
به نظر از دیکشنری بودنش هیچ استفاده‌ای نشده پس خوبه که این‌جا لیستی از کلاس
Doc
ریترن کنی

2021-03-28 14:45 UTC, mostmand commented on phase10/elasticsearch/SearchConnection/Analyzer.cs
> +        public static string CustomAnalyzer => "Ngram-Word_delimiter-Stop";
خوبه که در نام‌گذاری‌ها توی الستیک‌سرچ از یه استاندارد واحد پیروی کنی مثلا
kebab case
یا
snake case
یا
camel case
یا
pascal case
یا ...

2021-03-28 14:45 UTC, mostmand commented on phase10/elasticsearch/SearchConnection/ElasticClientFactory.cs
> +        private static readonly IElasticClient ElasticClient;
فیلدها توی سی‌شارپ
camelCase
هستن

2021-03-28 14:45 UTC, mostmand commented on phase10/elasticsearch/SearchConnection/ElasticClientFactory.cs
> +            ElasticClient = CreateClient();
به جای این اسکوپ استاتیک مقداردهی رو جلوی خود فیلد انجام بده یعنی همون بالای کلاس این جوری:
```csharp
private static readonly IElasticClient _elasticClient = CreateClient();
```

2021-03-28 14:45 UTC, mostmand commented on phase10/elasticsearch/SearchConnection/IndexCreator.cs
> +            return tokenFilters.
خوبه نقطه‌ها رو کنار خود عبارت بذاری منظورم این جوریه:
```csharp
return tokenFilters.Ngram(TokenFilter.NGram, s => s
    .MinGram(3)
    .MaxGram(10));
```
البته یه کم سلیقه‌ایه ولی به نظرم یه نقطه تو هر سطر باعث میشه خواناتر باشه

2021-03-28 14:45 UTC, mostmand commented on phase10/elasticsearch/SearchConnection/Searcher.cs
> +            //response.Validate();
چرا ولیدیت کامنت شده و 
Console.WriteLine()
صدا زده شده؟

2021-03-28 14:45 UTC, mostmand commented on phase10/elasticsearch/SearchConnection/TokenFilter.cs
> +        public static string NGram => "my-ngram-filter";
این‌جا هم اون استاندارد نام‌گذاری واحد که گفتم رعایت نشده

2021-03-28 15:01 UTC, mostmand commented on phase10/elasticsearch/Validation/ResponseValidator.cs
> +            throw exception.FailureReason switch
این‌جا سوییچ کیس زدی که میشه یه جوری ازش اجتناب کرد امیرحسین یه کم نزدیک شده به راه حل ولی اون هم باز کامل نیست راه حل اونو ببین و فکر کنید چه راه حل بهتری وجود داره

2021-03-28 16:14 UTC, hoseinaghaei commented on phase10/elasticsearch/Controller.cs
> +                    noSignWords = $"{noSignWords} {word}";
بله این مورد رو درست کردم و لیست کردمش با لینک ولی هنوز پوش نکردم

2021-03-28 16:15 UTC, hoseinaghaei commented on phase10/elasticsearch/DocManager/DocFileReader.cs
> +        public Dictionary<string, string> ScanData(string directoryPath)
حقیقت اینو باهاتون صحبت کرده بودم، بخاطر او سالید خواستم کد رو تغییر ندم و بجاش یک کلاس دیگه که داک میسازه زدم

2021-03-28 16:16 UTC, hoseinaghaei commented on phase10/elasticsearch/SearchConnection/Analyzer.cs
> +        public static string CustomAnalyzer => "Ngram-Word_delimiter-Stop";
اگر منظورتون اون دبلیو داخل وورد هست چون اسم فیلتر دقیقا به همین شکل بود من اینطوری نوشتم، به هرحال ممنون بابت این نکته!

2021-03-28 16:17 UTC, hoseinaghaei commented on phase10/elasticsearch/SearchConnection/ElasticClientFactory.cs
> +        private static readonly IElasticClient ElasticClient;
حقیقت خودمم کمل کیس زدم اما بخاطر استاتیک بودن پیشنهاد رایدر بود که پاسکالش کنم، الان تغییر بدم؟

2021-03-28 16:17 UTC, hoseinaghaei commented on phase10/elasticsearch/SearchConnection/ElasticClientFactory.cs
> +            ElasticClient = CreateClient();
حتما اصلاح میشه

2021-03-28 16:18 UTC, hoseinaghaei commented on phase10/elasticsearch/SearchConnection/IndexCreator.cs
> +            return tokenFilters.
بله خواناتر هست، تصحیح میشه حتما

2021-03-28 16:19 UTC, hoseinaghaei commented on phase10/elasticsearch/SearchConnection/Searcher.cs
> +            //response.Validate();
همش تقصیر باگه:)) باید پاک کنم کلا اونو

2021-03-28 16:19 UTC, hoseinaghaei commented on phase10/elasticsearch/SearchConnection/TokenFilter.cs
> +        public static string NGram => "my-ngram-filter";
بازم بخاطر استاتیکه

2021-03-28 16:22 UTC, mostmand commented on phase10/elasticsearch/SearchConnection/TokenFilter.cs
> +        public static string NGram => "my-ngram-filter";
نه منظورم سمت راستشه اسمی که تو الستیک قراره باشه

2021-03-31 05:21 UTC, mostmand approved these changes

2021-03-31 05:21 UTC, mostmand commented on phase10/elasticsearch/Validation/BadAuthenticationException.cs
> +    public abstract class BadAuthenticationException : IPipeLineException
اکسپشن چون یه تایپ خود سی‌شارپه و هر چیزی از جنس
Exception
باشه آخر اسمش اکسپشن داره خوبه یه نام بهتری واسه این کلاس‌ها بذاری

2021-03-31 05:21 UTC, mostmand commented on phase10/elasticsearch/Validation/ResponseValidator.cs
> +            if (Errors.ContainsKey((PipelineFailure) exception.FailureReason))
می‌تونی از تابع
GetValueOrDefault
دیکشنری استفاده کنی

2021-03-31 05:21 UTC, mostmand commented on phase10/elasticsearch/elasticsearch.csproj
> +      <PackageReference Include="Microsoft.Extensions.Configuration" Version="6.0.0-preview.2.21154.6" />
بهتره از ورژن‌های
stable
نوگت‌ها استفاده کنی نه ورژن‌های
preview

2021-04-03 07:05 UTC, mahdimalverdi approved these changes

2021-04-03 09:23 UTC, merged